site_name: Catenda Documentation
theme:
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
  name: material
  palette:
    primary: custom
extra_css:
  - stylesheets/extra.css
